#Symbols to be replaced before compilation

#Greek
s/α/alfa_/g
s/β/bta_/g
s/Γ/Gma_/g
s/γ/gma_/g
s/Δ/Dta_/g
s/δ/dta_/g
s/ϵ/eps_/g
s/ε/veps_/g
s/ζ/zta_/g
s/η/eta_/g
s/θ/thta_/g
s/ι/iota_/g
s/κ/kpa_/g
s/λ/lda_/g
s/μ/mu_/g
s/ν/nu_/g
s/ξ/xi_/g
#s/ο/omi_/g 
s/π/pi_/g
s/ρ/rho _/g 
s/σ/sgma_/g
s/τ/tau_/g
s/υ/ups_/g
s/φ/phi_/g
s/χ/chi_/g
s/ψ/psi_/g
s/ω/omga_/g

#Math
#s/⁺/pls_/g
#s/⁻/mns_/g
s/·/cdot_/g  #U+00B7
#s/⨯/times_/g #U+2A2F
#s/±/pm_/g
s/∂/partial_/g
s/∇/nbla_/g
#s/ᵀ/transp_/g
s/ᵃ/adj_/g
s/⁻¹/inv_/g
s/²/sq_/g
s/³/cbc_/g
s/√/sqrt_/g

##Arrows
#s/←/left_/g
#s/→/rght_/g
#s/↑/up_/g
#s/↓/dn_/g
#s/⊙/frnt_/g


#Nomenclature for public entities:
#i_   - integer type
#r_   - (single-precision) real type
#d_   - double-precision real type
#c_   - (single-precision) complex type
#z_   - double-precision complex type
#s_   - character or string type
#p_   - pointer
#t_   - derived type
#o_   - optional argument for procedures
#sub_ - subroutines
#m_   - module
#if_,is_ - logical type
#oif_,ois_ - logical type optional argument